# Generated by Django 5.1.3 on 2025-05-13 14:58

from django.db import migrations


def create_initial_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    groups_to_create = ['User', 'Editor', 'Administrator']
    for group_name in groups_to_create:
        group, created = Group.objects.get_or_create(name=group_name)
        if created:
            print(f"Группа '{group_name}' создана.")
        else:
            print(f"Группа '{group_name}' уже существует.")

def revert_initial_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['User', 'Editor', 'Administrator']).delete()
    print("Группы 'User', 'Editor', 'Administrator' удалены.")


class Migration(migrations.Migration):
    dependencies = [
        ('social_network', '0010_alter_friendrequest_unique_together_notification'),
        ('ai', '0003_videoprompt_ai_videoprompt_category_idx'),
        ('chat', '0003_message_chat_message_user_idx'),
    ]

    operations = [
        migrations.RunPython(create_initial_groups, reverse_code=revert_initial_groups),
    ]
