# Generated by Django 5.1.3 on 2025-05-13 19:55

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('social_network', '0011_initial_groups_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateExtension('pg_trgm'),
        migrations.AddIndex(
            model_name='comment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='comment_content_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='comment_created_at_brin_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='freq_created_brin_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='notif_ts_brin_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='post_title_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='post_content_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='post_created_at_brin_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['bio'], name='profile_bio_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
