# Generated by Django 5.1.3 on 2025-05-14 18:25

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("arrTitles", models.JSONField(blank=True, null=True)),
                ("arrImages", models.JSONField(blank=True, null=True)),
                ("arrVideos", models.JSONField(blank=True, null=True)),
                ("finalVideo", models.URLField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("comedy", "Comedy"),
                            ("tragedy", "Tragedy"),
                            ("humor", "Humor"),
                            ("romance", "Romance"),
                            ("horror", "Horror"),
                        ],
                        db_index=True,
                        default="comedy",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.search.SearchVector(
                            "prompt", config="pg_catalog.english"
                        ),
                        name="videoprompt_prompt_search_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["arrTitles"], name="videoprompt_arrtitles_gin_idx"
                    ),
                    django.contrib.postgres.indexes.BrinIndex(
                        fields=["created_at"], name="videoprompt_created_at_brin_idx"
                    ),
                ],
            },
        ),
    ]
