# Generated by Django 5.1.3 on 2025-05-14 17:07

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprompt',
            name='category',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('tragedy', 'Tragedy'), ('humor', 'Humor'), ('romance', 'Romance'), ('horror', 'Horror')], db_index=True, default='comedy', max_length=10),
        ),
        migrations.AddIndex(
            model_name='videoprompt',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('prompt', config='pg_catalog.english'), name='videoprompt_prompt_search_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprompt',
            index=django.contrib.postgres.indexes.GinIndex(fields=['arrTitles'], name='videoprompt_arrtitles_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprompt',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='videoprompt_created_at_brin_idx'),
        ),
    ]
