# Generated by Django 5.1.3 on 2025-05-13 20:11

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='videoprompt',
            index=django.contrib.postgres.indexes.GinIndex(fields=['arrTitles'], name='vp_arrtitles_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprompt',
            index=django.contrib.postgres.indexes.GinIndex(fields=['arrImages'], name='vp_arrimages_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprompt',
            index=django.contrib.postgres.indexes.GinIndex(fields=['arrVideos'], name='vp_arrvideos_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprompt',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='vp_created_at_brin_idx'),
        ),
    ]
