# Generated by Django 5.1.3 on 2025-05-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_videoprompt_vp_arrtitles_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='videoprompt',
            index=models.Index(fields=['category'], name='ai_videoprompt_category_idx'),
        ),
    ]
