# Generated by Django 5.1.3 on 2025-05-14 17:07

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='call',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['start_time'], name='call_start_time_brin_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('content', config='pg_catalog.english'), name='message_content_search_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='message_timestamp_brin_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='room_created_at_brin_idx'),
        ),
    ]
