# Generated by Django 5.1.3 on 2025-05-13 19:55

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateExtension('pg_trgm'),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='chat_message_content_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='msg_ts_brin_idx'),
        ),
    ]
