name: Simple CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: false
          load: true
          tags: cartoonix-backend:test

      - name: Build Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: false
          load: true
          tags: cartoonix-frontend:test
